# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
            ],
        ),
    ]
