# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-03-09 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Python技术', 'Python技术'), ('数据库技术', '数据库技术'), ('其他', '其他')], default=('Python技术', 'Python技术'), max_length=20),
        ),
    ]
